### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by LuciuzHQ** [Teal-c/rtModern-Remix#1]
Hello,

Thanks for your great themes !

I have a problem with the display, you can see a printscreen here:
https://imgur.com/1249eTa

Do you know why ?

Thanks.

**Comment by Teal-c** [comment]
Hello,
What script did you use to install rutorrent? 

It is the default theme of your installation that is causing the problem. Do you know which theme is default?

Depending on your answer, I will adapt the theme to fix bugs on your installation. Should be easy to fix, I'll get to it very quick.

**Comment by LuciuzHQ** [comment]
I have used the manual installation, not a script. I have used this tutorial:
https://mondedie.fr/d/11708-tuto-installer-rutorrent-sur-debian-11-nginx-php-fpm

My default theme is so:
`$defaultTheme = ""; // May be "", "Oblivion", "Dark", "Blue" or "Acid"`

Thanks.

**Comment by Teal-c** [comment]
T'es français, c'est plus simple ^^

J'ai l'impression qu'il y a des éléments qui ont changés sur la sidebar, par rapport à mon installation mondedie.fr avec Bobobox.
Je vais faire une installation récente avec le tuto que tu as utilisé, pour comparer et corriger le thème ces prochains jours puis je reviens vers toi quand c'est bon.

En attendant, si tu veux utiliser le thème, je te propose d'essayer cette solution dans dans le fichier custom.css : 
```
/var/www/rutorrent/plugins/theme/themes/rtModern-Remix/custom.css
```
de copier le code suivant, tout en bas, sous le `}`  :
```
#-_-_-all-_-_-, #-_-_-dls-_-_-, #-_-_-com-_-_-, #-_-_-act-_-_-, #-_-_-iac-_-_-, #-_-_-err-_-_- { background-image: none;}
div#CatList ul li span { background:transparent; }
```
Puis de vider le cache du navigateur pour être sûr que le css est bien chargé.

Je pense que ça devrait supprimer les pictos en fond et aussi le fond gris sous les stats.

**Comment by LuciuzHQ** [comment]
C'est vrai que c'est plus simple ainsi :-)

Malheureusement, cela n'a rien changé, j'ai bien vidé le cache et ajouté le code ainsi:

`    --color-input-text:#fff;`
`    --color-input-disable:#1c1f25;`
`}`
`#-_-_-all-_-_-, #-_-_-dls-_-_-, #-_-_-com-_-_-, #-_-_-act-_-_-, #-_-_-iac-_-_-, #-_-_-err-_-_- { background-image: none;}
div#CatList ul li span { background:transparent; }`

Est-ce bien correct ?

**Comment by Teal-c** [comment]
Oui c'est bien correct.
Je reviens, le temps de trouver un peu de disponibilité ces prochains jours/semaines pour me mettre dans la même situation que vous puis adapter le thème.

**Comment by Teal-c** [comment]
@BeAristobule , le thème est corrigé.
Il n'y a plus de problème avec les icônes de la sidebar.

Je pense que vous avez installé la version v4.0-beta.1 de ruTorrent.
Merci pour le rapport de bug :-)

Un aperçu avec le thème Plex.

![](https://i.imgur.com/tNDzZZ7.png)
