### ISSUE TITLE
ruTorrent 4.3 breaks sidebar

### ISSUE THREAD

**Issue by adelias** [Teal-c/rtModern-Remix#5]
Thanks for making these themes available!
After upgrading ruTorrent to version 4.3 the sidebar is broken on these themes.
Please look into this issue if possible.
Thanks!

**Comment by 3z3qu13l** [comment]
Sidebar looks like that on mine:
![image](https://github.com/Teal-c/rtModern-Remix/assets/34472031/4f510c66-9d86-41cc-a570-62a88117395c)

**Comment by LexaNz** [comment]
Same here

**Comment by Teal-c** [comment]
Hello, @adelias @3z3qu13l  @LexaNz 

I'm very pleased that these themes can be useful to everyone ;-)

The display bug on ruTorrent 4.3.0 is fixed and tested.

Feel free to give your feedback with screenshots if you see any other bugs.
Also, let me know which script you used for the installation so I can test with the same solution as you.

**EDIT : Think about clearing your browser's cache and restarting RuTorrent for the new theme and CSS to work.**

![1](https://github.com/Teal-c/rtModern-Remix/assets/70245242/910acc0a-0815-4b67-abc7-cf7794ccf79f)
![2](https://github.com/Teal-c/rtModern-Remix/assets/70245242/69135174-4122-4ec2-bbf1-0ba808dc817d)
![4](https://github.com/Teal-c/rtModern-Remix/assets/70245242/f9332ce0-c643-45d1-82da-df4290fe442d)

**Comment by 3z3qu13l** [comment]
LGTM, thanks a lot !
![image](https://github.com/Teal-c/rtModern-Remix/assets/34472031/99b19893-2e8b-4d03-ba39-d66ce1311c99)

I removed all existing themes and clone them back, no restart or cache issue
```bash
rm -rf rtModern-*
# rtModern-Remix
git clone https://github.com/Teal-c/rtModern-Remix.git rtModern-Remix
# rtModern-Plex-v2
git clone https://github.com/Teal-c/rtModern-Remix.git rtModern-Plex-v2
rm rtModern-Plex-v2/custom.css
cp rtModern-Plex-v2/themes/plex.css rtModern-Plex-v2/custom.css
# rtModern-Jellyfin-v2
git clone https://github.com/Teal-c/rtModern-Remix.git rtModern-Jellyfin-v2
rm rtModern-Jellyfin-v2/custom.css
cp rtModern-Jellyfin-v2/themes/jellyfin.css rtModern-Jellyfin-v2/custom.css
# rtModern-Jellyfin-v2-bg
git clone https://github.com/Teal-c/rtModern-Remix.git rtModern-Jellyfin-v2-bg
rm rtModern-Jellyfin-v2-bg/custom.css
cp rtModern-Jellyfin-v2-bg/themes/jellyfin-bg.css rtModern-Jellyfin-v2-bg/custom.css
# change owner/group
chown -R www-data:www-data rtModern-*
```

**Comment by adelias** [comment]
Many thanks for updating these themes!

**Comment by LexaNz** [comment]
Thanks for the quick fix, much appreciated !

**Comment by hdswiss** [comment]
Can you add a loading bar in when the torrent is finished so that it turns green?
Here is a picture of another theme.
<img width="215" alt="loadingbar" src="https://github.com/Teal-c/rtModern-Remix/assets/168787385/f661008f-f517-4e62-8c1d-ea960a7f590b">

**Comment by 3z3qu13l** [comment]
You should create another issue @hdswiss 
This one is resolved.

**EDIT**
Try to remove this code in style.css
`.meter-value{background:var(--color-torrents-list-percent)!important}`
